### PR TITLE
chore: Add travis

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@nikit19 @dreadpool2 @simarsingh24 Guys, please don't compromise with code quality. I saw some strange stuff in the app. I know you're on tight schedule, but GSOC is about learning as well. You must also learn how to design and architect applications, not just write code that technically works. 

If you spend 12 hours writing good code, you'll spend 20 hours fixing that code or maybe not as you move forward, you'll forget about it and it'd be written in stone. The greatest benefit of a greenfield project is that you get to do things right and make it correct from start. Coding this way will only make things worse for you guys in future and increase technical debt. 

Just see the way API token is handled in each class, this is loitering. I'll be creating an isolated component tomorrow to encapsulate the logic in it. Please follow suit in thinking and designing before coding and you'll see your code shine after these 4 months

**Comment by dreadpool2** [comment]
@iamareebjamal Should I send the PR about the creation of the Login activity Viewmodel now. I had sent it to the previous repo. Or should I do it after you share your details tomorrow?

**Comment by iamareebjamal** [comment]
@dreadpool2 It's not about MMVM for now. Even after introducing MVVM, it the architecture is not correct, things will be bleak. MVVM MVP is presentation technology. The backend services should be well made first. This is something you should do as you code. Hopefully, I will create an example tomorrow on how to handle encapsulation of logic. Some of the stuff has been done in this PR as well

**Comment by dreadpool2** [comment]
@iamareebjamal Great :+1:

**Pull request merged**
